// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxOc3VjYqVGWTllaGwF2FtOJK7bPe-gOs',
    appId: '1:1054751727574:web:0efe70ba6beb2595114e77',
    messagingSenderId: '1054751727574',
    projectId: 'mobile-9fdc4',
    authDomain: 'mobile-9fdc4.firebaseapp.com',
    storageBucket: 'mobile-9fdc4.firebasestorage.app',
    measurementId: 'G-J78Y8GX2JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyXdkbsMQFQjoCzinSQ1AC7aSSSSAIpJk',
    appId: '1:1054751727574:android:f1f5e3d4bff790a7114e77',
    messagingSenderId: '1054751727574',
    projectId: 'mobile-9fdc4',
    storageBucket: 'mobile-9fdc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48L6t4_vvKDNQi-CVLP4aOffHF2qrOmk',
    appId: '1:1054751727574:ios:ecd3c39bc356d9c0114e77',
    messagingSenderId: '1054751727574',
    projectId: 'mobile-9fdc4',
    storageBucket: 'mobile-9fdc4.firebasestorage.app',
    iosBundleId: 'com.example.justCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA48L6t4_vvKDNQi-CVLP4aOffHF2qrOmk',
    appId: '1:1054751727574:ios:ecd3c39bc356d9c0114e77',
    messagingSenderId: '1054751727574',
    projectId: 'mobile-9fdc4',
    storageBucket: 'mobile-9fdc4.firebasestorage.app',
    iosBundleId: 'com.example.justCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxOc3VjYqVGWTllaGwF2FtOJK7bPe-gOs',
    appId: '1:1054751727574:web:56a1c05dd8c4a185114e77',
    messagingSenderId: '1054751727574',
    projectId: 'mobile-9fdc4',
    authDomain: 'mobile-9fdc4.firebaseapp.com',
    storageBucket: 'mobile-9fdc4.firebasestorage.app',
    measurementId: 'G-C8SQVJZW6N',
  );
}
